version: "3"
services:
  libre1:
    build:
      context: .
  libre2:
    build:
      context: .
  libre3:
    build:
      context: .
  balancer:
    image: "nginx:1.13.5-alpine"
    ports:
      - "6000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
